README.md
jadbio/Dockerfile
jadbio/job_inputs/jadbio-inputs.yml
jadbio/tools/jadbio-pred.cwl

JADBio cwl workflow complete and set up for all 26 cancer cohorts. future tasks include to format the output into the universal format for output files.

Jadbio cwl

---

skgrid/Dockerfile
skgrid/image_scripts/run_train.py
skgrid/image_scripts/train.sh
skgrid/pick_model.py
skgrid/select_model.yml

adds functionality for multiple models per cancer cohort (set up framework for having a best overall model and best single platform models)

Skgrid extended

---

README.md
user-job-ymls/aklimate-inputs.yml
user-job-ymls/subscope-inputs.yml

expand readme sections and add generic user input tips

Method details

---

README.md
RUN_MODEL.sh
cloudforest/README.md
cloudforest/RUN.sh
cloudforest/tools/cloudforest-pred.cwl
cloudforest/tools/transpose.py
cloudforest/workflows/ml_workflow.cwl
tools/create_jobs.py
tools/transpose.py
user-job-ymls/cloudforest-inputs.yml

auto builds cwl yaml files based on a simplified user input. no longer user needs to edit yaml files directly
add specifications cancer, model, method, and user data at commandline (RUN_MODEL.sh)
completed for CloudForest

Cf all models

---

README.md
RUN_MODEL.sh
aklimate/README.md
skgrid/RUN.sh
tools/create_jobs.py
user-job-ymls/aklimate-inputs.yml
user-job-ymls/skgrid-inputs.yml
user-job-ymls/subscope-inputs.yml

auto generates cwl job yamls to simplify user input
includes: aklimate, sk grid, subscope
already included in previous PR: cloudforest
TODO: jadbio (blocker is waiting for models from jadbio team)

Remain auto yaml

---

RUN_MODEL.sh
aklimate/README.md
requirements.txt
tools/create_jobs.py
tools/options.yml
tutorial/README.md

force stop if error 
test to validate method-cancer-platform combo
add tools/options.yml to see all valid combos
update tutorial

Yaml extension

---

cloudforest/tools/cloudforest-pred.cwl
cloudforest/workflows/ml_workflow.cwl

update synapse docker image and docker pull to use cloudforest model for all data types

cf synapse docker image

---

aklimate/RUN.sh
aklimate/preds/info.md
cloudforest/preds/info.md
jadbio/RUN.sh
jadbio/preds/info.md
skgrid/RUN.sh
skgrid/preds/info.md
subscope/RUN.sh
subscope/preds/info.md

update all methods to output prediction file(s) to `<method>/preds/` to make it cleaner for user

Preds location

---

README.md
subscope/README.md
subscope/tools/subscope-pred.cwl
subscope/workflows/ml_workflow.cwl
tools/options.yml

modify with latest version 2 of subscope. optional to specify cancer cohort, if none is supplied then uses pan can model

Subscope expand

---

tools/convert.py
tutorial/README.md
user-transformed-data/info.md

add command line options for preprocessing data and update readmes

Prepro extended

---

skgrid/RUN.sh

output directly to preds dir and move around model grid and trained pickle file

output to preds

---

README.md

Remove extraneous quote after UVM
Edit requirements file extention

Edit tutorial on README.md

---

README.md

typo fixes and expand on model data download

Model data

---

user-job-ymls/aklimate-inputs.yml
user-job-ymls/cloudforest-inputs.yml
user-job-ymls/info.md
user-job-ymls/jadbio-inputs.yml
user-job-ymls/skgrid-inputs.yml
user-job-ymls/subscope-inputs.yml

info file to describe use and rm yml artifacts

---

skgrid/Dockerfile
tutorial/error_messages.md

update users, labels and streamline dockerfile of skgrid
add help message for troubleshooting

Skgrid dockerfile and add troubleshooting

---

README.md

add numbers to clarify flow of setup section

numbered setup

---

README.md
tutorial/error_messages.md

Updates to data and other links. Announcement of native support of tensorflow for M1 Apple machines

Data links and M1 Apple Support

---

README.md
tools/run_transform.sh
tutorial/README.md

specify any cancer cohort to run transform script. and update other code to point at these matrices 
update docs to reflect this

Universal transform

---

README.md
tools/zero_floor.py
tutorial/README.md

Add utility for when 10th quantile lower in target data than in source data.

handles when 10Q TMP lower than user input

---

tools/convert.py
tutorial/README.md

match the location of the reference file as mentioned in the readme

clean up tooling folder

---

README.md

Add links to the manuscript publication and the publication page for data download

Publication links

---

README.md
tools/tools_ml.py

To inspect model details using the tools_ml module, users will need to download the required file `model_info.json` from the publication page.

download instruction updated
